# from agents.query_agent import generate_query
# from agents.validation_agent import validate_query
# from agents.explanation_agent import explain_query
# from agents.schema_agent import get_schema

# def run_pipeline(db, user_query):
#     try:
#         print("\n🧠 User Query:", user_query)

#         # =========================================================
#         # 1. DYNAMIC SCHEMA AGENT
#         # =========================================================
#         try:
#             schema = get_schema(db)
#         except Exception:
#             # Fallback if your database.schema_extractor isn't fully ready
#             schema = """
#             Collections:
#             - users: [name, email, age]
#             - movies: [title, genre, rating]
#             """

#         # =========================================================
#         # 2. QUERY GENERATION AGENT
#         # =========================================================
#         query_dict = generate_query(user_query, schema)
#         print("⚙️ Generated Query:", query_dict)

#         if not isinstance(query_dict, dict):
#             return {"error": "Invalid query format generated by LLM. Expected dictionary."}

#         # =========================================================
#         # 3. VALIDATION AGENT
#         # =========================================================
#         is_valid, msg = validate_query(query_dict)
#         if not is_valid:
#             return {"error": msg}

#         # =========================================================
#         # 4. EXPLANATION AGENT (Dynamic Explanation)
#         # =========================================================
#         # Explain the generated query dict before executing it
#         explanation = explain_query(str(query_dict))

#         # =========================================================
#         # 5. GET COLLECTION 
#         # =========================================================
#         collection_name = query_dict.get("collection")

#         if not collection_name:
#             return {"error": "No collection specified in the generated query"}

#         collection = db[collection_name]

#         # =========================================================
#         # 6. HANDLE INSERT
#         # =========================================================
#         if query_dict.get("operation") == "insert":
#             data = query_dict.get("data", {})

#             if not data:
#                 return {"error": "No data provided for insert operation"}

#             result = collection.insert_one(data)

#             return {
#                 "query": query_dict,
#                 "explanation": explanation,
#                 "result": f"✅ Document added with ID: {str(result.inserted_id)}"
#             }

#         # =========================================================
#         # 7. HANDLE FIND
#         # =========================================================
#         elif query_dict.get("operation") == "find":
#             filter_query = query_dict.get("filter", {})
#             projection_query = query_dict.get("projection", None) # None implies fetch all fields if empty

#             # Only pass projection if it's explicitly populated, otherwise pass None to avoid Mongo errors
#             if not projection_query:
#                 cursor = collection.find(filter_query)
#             else:
#                 cursor = collection.find(filter_query, projection_query)
                
#             results = list(cursor)

#             if not results:
#                 return {
#                     "query": query_dict,
#                     "explanation": explanation,
#                     "result": []
#                 }

#             # Clean output (convert ObjectId to string for JSON serialization)
#             cleaned_results = []
#             for doc in results:
#                 doc["_id"] = str(doc["_id"])
#                 cleaned_results.append(doc)

#             return {
#                 "query": query_dict,
#                 "explanation": explanation,
#                 "result": cleaned_results
#             }

#         # =========================================================
#         # 8. UNKNOWN OPERATION
#         # =========================================================
#         else:
#             return {"error": f"Unsupported operation: {query_dict.get('operation')}"}

#     except Exception as e:
#         print("🔥 ERROR:", str(e))
#         return {"error": str(e)}

from agents.query_agent import generate_query
from agents.validation_agent import validate_query
from agents.explanation_agent import explain_query
from agents.schema_agent import get_schema

def run_pipeline(db, user_query):
    try:
        print("\n🧠 User Query:", user_query)

        # =========================================================
        # 1. DYNAMIC SCHEMA AGENT
        # =========================================================
        try:
            schema = get_schema(db)
        except Exception:
            schema = """
            Collections:
            - users: [name, email, age]
            - movies: [title, genre, rating]
            """

        # =========================================================
        # 2. QUERY GENERATION AGENT
        # =========================================================
        query_dict = generate_query(user_query, schema)
        print("⚙️ Generated JSON:", query_dict)

        if not isinstance(query_dict, dict):
            return {"error": "Invalid JSON format generated by LLM. Expected dictionary."}

        operation = query_dict.get("operation")

        # =========================================================
        # 3. VALIDATION AGENT
        # =========================================================
        is_valid, msg = validate_query(query_dict)
        if not is_valid:
            return {"error": f"Validation Failed: {msg}"}

        # =========================================================
        # 4. EXPLANATION AGENT
        # =========================================================
        explanation = explain_query(str(query_dict))

        # =========================================================
        # 5. GET COLLECTION 
        # =========================================================
        collection_name = query_dict.get("collection")
        if not collection_name:
            return {"error": "No collection specified in the generated query"}

        collection = db[collection_name]

        # =========================================================
        # 6. EXECUTION BLOCK (CRUD + Analytics)
        # =========================================================
        
        # --- Handle Insert ---
        if operation == "insert":
            data = query_dict.get("data", {})
            if not data:
                return {"error": "No data provided for insert operation"}
            
            result = collection.insert_one(data)
            return {
                "query": query_dict,
                "explanation": explanation,
                "result": f"✅ Document added with ID: {str(result.inserted_id)}"
            }

        # --- Handle Find ---
        elif operation == "find":
            filter_query = query_dict.get("filter", {})
            projection_query = query_dict.get("projection", None) 

            if not projection_query:
                cursor = collection.find(filter_query)
            else:
                cursor = collection.find(filter_query, projection_query)
                
            results = list(cursor)

            if not results:
                return {
                    "query": query_dict,
                    "explanation": explanation,
                    "result": []
                }

            cleaned_results = []
            for doc in results:
                doc["_id"] = str(doc["_id"])
                cleaned_results.append(doc)

            return {
                "query": query_dict,
                "explanation": explanation,
                "result": cleaned_results
            }

        # --- Handle Aggregate (Analytics) ---
        elif operation == "aggregate":
            pipeline = query_dict.get("pipeline", [])
            
            if not pipeline:
                return {"error": "No pipeline provided for aggregation"}

            cursor = collection.aggregate(pipeline)
            results = list(cursor)

            if not results:
                return {
                    "query": query_dict,
                    "explanation": explanation,
                    "result": []
                }

            cleaned_results = []
            for doc in results:
                if "_id" in doc:
                    doc["_id"] = str(doc["_id"])
                cleaned_results.append(doc)

            return {
                "query": query_dict,
                "explanation": explanation,
                "result": cleaned_results
            }

        # --- Handle Update ---
        elif operation == "update":
            filter_query = query_dict.get("filter", {})
            update_data = query_dict.get("update_data", {})

            if not update_data:
                return {"error": "No update data provided (e.g., missing $set)"}

            result = collection.update_many(filter_query, update_data)

            return {
                "query": query_dict,
                "explanation": explanation,
                "result": f"✅ Update successful. Modified {result.modified_count} document(s)."
            }

        else:
            return {"error": f"Unsupported operation: {operation}"}

    except Exception as e:
        print("🔥 ERROR:", str(e))
        return {"error": str(e)}