# from agents.query_agent import generate_query
# from agents.validation_agent import validate_query
# from agents.explanation_agent import explain_query
# from agents.schema_agent import get_schema

# def run_pipeline(db, user_query):
#     try:
#         print("\n🧠 User Query:", user_query)

#         # =========================================================
#         # 1. DYNAMIC SCHEMA AGENT
#         # =========================================================
#         try:
#             schema = get_schema(db)
#         except Exception:
#             # Fallback if your database.schema_extractor isn't fully ready
#             schema = """
#             Collections:
#             - users: [name, email, age]
#             - movies: [title, genre, rating]
#             """

#         # =========================================================
#         # 2. QUERY GENERATION AGENT
#         # =========================================================
#         query_dict = generate_query(user_query, schema)
#         print("⚙️ Generated Query:", query_dict)

#         if not isinstance(query_dict, dict):
#             return {"error": "Invalid query format generated by LLM. Expected dictionary."}

#         # =========================================================
#         # 3. VALIDATION AGENT
#         # =========================================================
#         is_valid, msg = validate_query(query_dict)
#         if not is_valid:
#             return {"error": msg}

#         # =========================================================
#         # 4. EXPLANATION AGENT (Dynamic Explanation)
#         # =========================================================
#         # Explain the generated query dict before executing it
#         explanation = explain_query(str(query_dict))

#         # =========================================================
#         # 5. GET COLLECTION 
#         # =========================================================
#         collection_name = query_dict.get("collection")

#         if not collection_name:
#             return {"error": "No collection specified in the generated query"}

#         collection = db[collection_name]

#         # =========================================================
#         # 6. HANDLE INSERT
#         # =========================================================
#         if query_dict.get("operation") == "insert":
#             data = query_dict.get("data", {})

#             if not data:
#                 return {"error": "No data provided for insert operation"}

#             result = collection.insert_one(data)

#             return {
#                 "query": query_dict,
#                 "explanation": explanation,
#                 "result": f"✅ Document added with ID: {str(result.inserted_id)}"
#             }

#         # =========================================================
#         # 7. HANDLE FIND
#         # =========================================================
#         elif query_dict.get("operation") == "find":
#             filter_query = query_dict.get("filter", {})
#             projection_query = query_dict.get("projection", None) # None implies fetch all fields if empty

#             # Only pass projection if it's explicitly populated, otherwise pass None to avoid Mongo errors
#             if not projection_query:
#                 cursor = collection.find(filter_query)
#             else:
#                 cursor = collection.find(filter_query, projection_query)
                
#             results = list(cursor)

#             if not results:
#                 return {
#                     "query": query_dict,
#                     "explanation": explanation,
#                     "result": []
#                 }

#             # Clean output (convert ObjectId to string for JSON serialization)
#             cleaned_results = []
#             for doc in results:
#                 doc["_id"] = str(doc["_id"])
#                 cleaned_results.append(doc)

#             return {
#                 "query": query_dict,
#                 "explanation": explanation,
#                 "result": cleaned_results
#             }

#         # =========================================================
#         # 8. UNKNOWN OPERATION
#         # =========================================================
#         else:
#             return {"error": f"Unsupported operation: {query_dict.get('operation')}"}

#     except Exception as e:
#         print("🔥 ERROR:", str(e))
#         return {"error": str(e)}

from typing import Any, Optional
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, END

from agents.query_agent import generate_query
from agents.validation_agent import validate_query
from agents.explanation_agent import explain_query
from agents.schema_agent import get_schema

import datetime
from bson import ObjectId, Decimal128


def _sanitize(value):
    """Recursively convert BSON / non-JSON-serializable types to plain Python."""
    if isinstance(value, ObjectId):
        return str(value)
    if isinstance(value, Decimal128):
        return float(value.to_decimal())
    if isinstance(value, datetime.datetime):
        return value.isoformat()
    if isinstance(value, datetime.date):
        return value.isoformat()
    if isinstance(value, dict):
        return {k: _sanitize(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_sanitize(v) for v in value]
    return value


def sanitize_doc(doc: dict) -> dict:
    return _sanitize(doc)


# =========================================================
# PIPELINE STATE
# =========================================================
MAX_RETRIES = 2

class PipelineState(TypedDict):
    db: Any
    user_query: str
    history: Optional[list]
    schema: Optional[Any]
    query_dict: Optional[dict]
    is_valid: Optional[bool]
    validation_msg: Optional[str]
    explanation: Optional[str]
    result: Optional[Any]
    error: Optional[str]
    retry_count: int
    last_error: Optional[str]


# =========================================================
# NODE 1: Schema Agent
# =========================================================
def schema_node(state: PipelineState) -> PipelineState:
    print("\n[LangGraph] Node: schema_node")
    try:
        schema = get_schema(state["db"])
    except Exception:
        schema = {"users": ["name", "email", "age"], "movies": ["title", "genre", "rating"]}
    return {**state, "schema": schema}


# =========================================================
# NODE 2: Query Generation Agent
# =========================================================
def query_node(state: PipelineState) -> PipelineState:
    print(f"[LangGraph] Node: query_node (attempt {state.get('retry_count', 0) + 1})")
    try:
        query_dict = generate_query(
            state["user_query"],
            state["schema"],
            feedback=state.get("last_error"),
            history=state.get("history") or []
        )
        print("⚙️ Generated JSON:", query_dict)
        if not isinstance(query_dict, dict):
            return {**state, "error": "Invalid JSON format from LLM. Expected a dictionary."}
        return {**state, "query_dict": query_dict, "error": None}
    except Exception as e:
        return {**state, "error": f"Query generation failed: {str(e)}"}


# =========================================================
# NODE 3: Validation Agent
# =========================================================
def validation_node(state: PipelineState) -> PipelineState:
    print("[LangGraph] Node: validation_node")
    is_valid, msg = validate_query(state["query_dict"])
    return {**state, "is_valid": is_valid, "validation_msg": msg}


# =========================================================
# NODE 4: Explanation Agent
# =========================================================
def explanation_node(state: PipelineState) -> PipelineState:
    print("[LangGraph] Node: explanation_node")
    try:
        explanation = explain_query(str(state["query_dict"]))
        return {**state, "explanation": explanation}
    except Exception as e:
        return {**state, "explanation": f"Could not generate explanation: {str(e)}"}


# =========================================================
# NODE 5: Execution Agent
# =========================================================
def execution_node(state: PipelineState) -> PipelineState:
    print("[LangGraph] Node: execution_node")
    query_dict = state["query_dict"]
    db = state["db"]
    operation = query_dict.get("operation")

    collection_name = query_dict.get("collection")
    if not collection_name:
        return {**state, "error": "No collection specified in the generated query"}

    collection = db[collection_name]

    try:
        if operation == "insert":
            data = query_dict.get("data", {})
            if not data:
                return {**state, "error": "No data provided for insert operation"}
            result = collection.insert_one(data)
            return {**state, "result": f"✅ Document added with ID: {str(result.inserted_id)}"}

        elif operation == "find":
            filter_query = query_dict.get("filter", {})
            projection_query = query_dict.get("projection", None)
            cursor = collection.find(filter_query) if not projection_query else collection.find(filter_query, projection_query)
            results = list(cursor)
            cleaned = [sanitize_doc(doc) for doc in results]
            return {**state, "result": cleaned}

        elif operation == "aggregate":
            pipeline = query_dict.get("pipeline", [])
            if not pipeline:
                return {**state, "error": "No pipeline provided for aggregation"}
            results = list(collection.aggregate(pipeline))
            cleaned = [sanitize_doc(doc) for doc in results]
            return {**state, "result": cleaned}

        elif operation == "update":
            filter_query = query_dict.get("filter", {})
            update_data = query_dict.get("update_data", {})
            if not update_data:
                return {**state, "error": "No update data provided (e.g., missing $set)"}
            result = collection.update_many(filter_query, update_data)
            return {**state, "result": f"✅ Update successful. Modified {result.modified_count} document(s)."}

        else:
            return {**state, "error": f"Unsupported operation: {operation}"}

    except Exception as e:
        return {**state, "error": f"Execution failed: {str(e)}"}


# =========================================================
# NODE: Retry
# =========================================================
def retry_node(state: PipelineState) -> PipelineState:
    count = state.get("retry_count", 0) + 1
    print(f"[LangGraph] Node: retry_node (retry {count}/{MAX_RETRIES})")
    return {
        **state,
        "retry_count": count,
        "last_error": state.get("error") or state.get("validation_msg"),
        "error": None,
        "query_dict": None,
        "is_valid": None,
        "validation_msg": None,
    }


# =========================================================
# CONDITIONAL EDGES
# =========================================================
def after_query(state: PipelineState) -> str:
    if state.get("error"):
        if state.get("retry_count", 0) < MAX_RETRIES:
            return "retry"
        return "end"
    return "validate"


def after_validation(state: PipelineState) -> str:
    if not state.get("is_valid"):
        if state.get("retry_count", 0) < MAX_RETRIES:
            return "retry"
        return "end"
    return "explain"


# =========================================================
# BUILD LANGGRAPH WORKFLOW
# =========================================================
def build_graph():
    graph = StateGraph(PipelineState)

    graph.add_node("schema", schema_node)
    graph.add_node("query", query_node)
    graph.add_node("validate", validation_node)
    graph.add_node("retry", retry_node)
    graph.add_node("explain", explanation_node)
    graph.add_node("execute", execution_node)

    graph.set_entry_point("schema")
    graph.add_edge("schema", "query")
    graph.add_conditional_edges("query", after_query, {
        "validate": "validate",
        "retry": "retry",
        "end": END,
    })
    graph.add_conditional_edges("validate", after_validation, {
        "explain": "explain",
        "retry": "retry",
        "end": END,
    })
    graph.add_edge("retry", "query")  # loop back
    graph.add_edge("explain", "execute")
    graph.add_edge("execute", END)

    return graph.compile()


_compiled_graph = build_graph()


# =========================================================
# PUBLIC ENTRY POINT (keeps existing interface intact)
# =========================================================
def run_pipeline(db, user_query: str, history: list = None) -> dict:
    print("\n🧠 User Query:", user_query)

    initial_state: PipelineState = {
        "db": db,
        "user_query": user_query,
        "history": history,
        "schema": None,
        "query_dict": None,
        "is_valid": None,
        "validation_msg": None,
        "explanation": None,
        "result": None,
        "error": None,
        "retry_count": 0,
        "last_error": None,
    }

    final_state = _compiled_graph.invoke(initial_state)

    if final_state.get("error"):
        return {"error": final_state["error"]}
    if final_state.get("validation_msg") and not final_state.get("is_valid"):
        return {"error": f"Validation Failed: {final_state['validation_msg']}"}

    return {
        "query": final_state["query_dict"],
        "explanation": final_state["explanation"],
        "result": final_state["result"] if final_state["result"] is not None else [],
    }